In [1]:
import pandas as pd

In [2]:
path_folder = "Datasets/"
path_claims = "ClaimDetails_for_distribution.xlsx"
path_adjuster = "CatRosterReportDayOf_for_distribution_cleaned.xlsx"
path_dictionary = "Data_Set_decode_table_updated.xlsx"

In [3]:
ds_dictionary_claims = pd.read_excel(
    path_folder+path_dictionary,
    sheet_name=0
)

ds_dictionary_adjuster = pd.read_excel(
    path_folder+path_dictionary,
    sheet_name=1
)

ds_claims_main = pd.read_excel(
    path_folder+path_claims,
    sheet_name=0
)

ds_claims_explore = pd.read_excel(
    path_folder+path_claims,
    sheet_name=1
)

ds_adjuster_main = pd.read_excel(
    path_folder+path_adjuster,
    sheet_name=0
)

ds_adjuster_explore = pd.read_excel(
    path_folder+path_adjuster,
    sheet_name=1
)

In [16]:
ds_claims_main["Weather Text"].sort_values().unique()

array(['Flood                                                                           ',
       'Hail                                                                            ',
       'Hurricane or Tropical Storm - No Flooding                                       ',
       'Lightning (No Fire)                                                             ',
       'Non-submersion                                                                  ',
       'Other Flood                                                                     ',
       'Other Water Damage - weather                                                    ',
       'Other than Tornado, Hurricane, Tropical Storm - No Flooding                     ',
       'Other than Tornado, Hurricane, Tropical Storm with Flooding                     ',
       'Roof/Flashing Leak                                                              ',
       'Sewer/drain back-up                                                             ',

In [6]:
ds_adjuster_main["Org Group"].sort_values().unique()

array([' ', 'Auto-Heavy Equipment', 'Auto-Product Development',
       "Business Insurance Claim-CAE's", 'Business Intelligence & Analyt',
       'Claim Shared Service-Business Process Services',
       'Claim Shared Service-CCS WKFC Mgmt & Analytics',
       'Claim University-Claim University', 'Connecticut',
       'Field & Financial Services-Claim Workforce Effectiveness',
       'Field & Financial Services-Mgmt  Finance & Strategy',
       'Field Operations-Metro New York - New Jersey',
       'Field Operations-Southern',
       'Field Operations-Southern California',
       'Finance & Fld Shd Svcs-ETM & Fraud Analytics',
       'Finance & Fld Shd Svcs-Shared & Vendor Services',
       'Finance-Claim-Finance', 'Florida',
       'General Liability-Complex Case',
       'General Liability-Field General Liability', 'Lake Michigan',
       'Metro New York - New Jersey', 'Mid-Atlantic', 'Mountain West',
       'New England', 'North Texas - Oklahoma',
       'Northern California - Nevada

In [7]:
ds_adjuster_main["Preferred Role"].sort_values().unique()

array(['Auto Appraiser', 'Auto Claim Unit Mgr', 'FNOL',
       'Property Claim Unit Mgr', 'Property Field Inspector',
       'Property Inside Claim Rep', 'Property Outside Claim Rep',
       'Property Outside Contents Claim Rep', 'Supervisor', nan],
      dtype=object)

In [10]:
ds_adjuster_main["Location"].sort_values().unique()

array(['Albany - Park Pl', 'Albuquerque-Lang Avenue',
       'Alpharetta-Atlanta', 'Austin-901 Mo-Pac', 'Bedford - Commerce',
       'Birmingham-Hoover', 'Blue Bell-Phil-Lakeview Dr',
       'Boise-Meridian', 'Boston-Financial Center',
       'Brookfield-Milwaukee', 'Buffalo', 'Centennial-Denver-Geddes',
       'Chantilly-WashingtnDC-PkMeadow', 'Charlotte-Carmel Commons',
       'Cincinnati-Elsinore', 'Columbus-Easton Oval',
       'Delaware - Virtual', 'Diamond Bar-Los Angeles',
       'Durham - Emperor Blvd', 'Edison-343 Thornall',
       'Exton-Philadelphia-Eagleview', 'Federal Way-Seattle-6th Ave',
       'Flowood-Jackson-Canebrake', 'Franklin-Nashville', 'Fresno',
       'Glendale-LosAngeles-655NCentrl', 'Glens Falls - Queensbury',
       'Hamden Law', 'Hartford - Tower', 'Hartford-Field', 'Honolulu',
       'Houston - Westway', 'Hudson - Boston',
       'Hunt Valley-Baltimore-Schilling', 'Independence-Cleveland',
       'Indianapolis - 96th St', 'Irvine-Los Angeles-Michelson',
  

In [8]:
ds_adjuster_main["HR Job Title"].sort_values().unique()

array(['AVP, Claim Management', 'AVP, Complex Claim Liability',
       'AVP, Complex Claim Liability Specialist',
       'Account Underwriter, BSI Private Non-Profit', 'Acct Exec, BC',
       'Assoc Acct Exec, BSI Financial Institutions',
       'Assoc Acct Exec, BSI Private Non-Profit',
       'Assoc Acct Exec, Inland', 'Assoc Acct Exec, Oil & Gas',
       'Assoc Acct Exec, Select', 'Auto Salvage Coordinator', 'BI UPDP',
       'Benefit Management Case Manager',
       'Benefit Management Complex Case Manager', 'Benefit Mgmt Analyst',
       'Claim Account Executive', 'Claim Product Manager',
       'Claim Rep Trainee, Outside Property',
       'Claim Rep Trainee, Property Resolution',
       'Claim Rep Trainee, Subrogation',
       'Claim Rep Trainee, Workers Compensation',
       'Claim Rep, Auto Damage Specialist', 'Claim Rep, Auto FPM',
       'Claim Rep, Auto FPM Litigation/Arbitration', 'Claim Rep, Auto I',
       'Claim Rep, Auto II', 'Claim Rep, Auto Liability',
       'Claim 

In [9]:
ds_adjuster_main["HR Job Title"]

0      Claim Rep Trainee, Outside Property
1      Claim Rep Trainee, Outside Property
2      Claim Rep Trainee, Outside Property
3      Claim Rep Trainee, Outside Property
4      Claim Rep Trainee, Outside Property
                      ...                 
769         Tech Spec, Specialty Liability
770                       OLDP Participant
771          Sr Dir, Bus Perform Analytics
772                Unit Manager, Claim Ops
773                 Outside Auto Appraiser
Name: HR Job Title, Length: 774, dtype: object

In [ ]:
titles = (
    ds_adjuster_main["HR Job Title"]
    .dropna()
    .str.lower()
    .str.strip()
)

In [ ]:
JOB_TITLE_RULES = {
    "manager": [
        "manager",
        "mgr",
        "supervisor",
        "lead"
    ],
    "senior_adjuster": [
        "senior adjuster",
        "sr adjuster",
        "sr."
    ],
    "adjuster": [
        "adjuster",
        "claims rep",
        "claims representative"
    ],
    "analyst": [
        "analyst",
        "analysis"
    ],
    "director": [
        "director",
        "head of"
    ],
    "assistant": [
        "assistant",
        "asst"
    ]
}


In [13]:
ds_adjuster_main["Preferred Tour Length"].sort_values().unique()

array([14., 21., 28., nan])

In [16]:
ds_adjuster_main["Worksite Name"].unique()

array([nan, 'NCC Virtual FRT Support                           ',
       'Minneapolis, MN                                   ',
       'Cleveland, OH                                     ',
       'Natomas, CA                                       ',
       'Topeka, KS                                        ',
       'Lone Tree, CO                                     ',
       'Auto - Lawton, OK                                 ',
       'Greenville, SC                                    ',
       'Newton, IA                                        ',
       'White Plains, NY                                  ',
       'Auto - Little Rock, AR                            ',
       'Jamaica, NY                                       ',
       'New Stanton, PA                                   ',
       'Lexington, KY                                     ',
       'Sacramento, CA                                    ',
       'West Salem, WI                                    ',
       'Little Rock

In [75]:
ds_claims_main["Policy Form Desc"].unique()

array(['SPECIAL HOMEOWNERS FORM - DWELLING (HOMEPAC)                                                        ',
       'Commercial Property Deluxe Program - Simp. OCC. BI / Comm Mult Peril                                ',
       'MPAC CLAIMS MADE - OCCURRENCE                                                                       ',
       'High Value Home                                                                                     ',
       'TENANTS FORM (HOMEPAC)                                                                              ',
       'Landlord Dwelling Form                                                                              ',
       'CONDOMINIUM HOME OWNERS FORM (HOMEPAC)                                                              ',
       'RENTAL DWELLING FORM (HOMESAVER)                                                                    ',
       'Farm - BI Package Simp. o/t f/r Comb. Coverage Plan BI / Comm Mult Peril                            ',
 

In [21]:
ds_claims_main["Peril Group"].unique()

array(['Wind', 'Hail', 'Water (W)', 'All Other Weather'], dtype=object)

In [22]:
ds_claims_main["Weather Text"].unique()

array(['Tornado - No Flooding                                                           ',
       'Hail                                                                            ',
       'Other than Tornado, Hurricane, Tropical Storm - No Flooding                     ',
       'Flood                                                                           ',
       'Roof/Flashing Leak                                                              ',
       'Lightning (No Fire)                                                             ',
       'Other Water Damage - weather                                                    ',
       'Water Seepage in Basement not from Sewer or Sump Back-Up                        ',
       'Other than Tornado, Hurricane, Tropical Storm with Flooding                     ',
       'Hurricane or Tropical Storm - No Flooding                                       ',
       'Sump Overflow                                                                   ',

In [24]:
ds_adjuster_main["Deployed Role"].unique()

array([nan, 'Property Outside Claim Rep', 'Property Inside Claim Rep',
       'Auto Appraiser', 'Property Claim Unit Mgr',
       'Property Field Inspector', 'Property Outside Contents Claim Rep',
       'Auto Claim Unit Mgr',
       'Auto Inside Claim Rep - Personal Insurance', 'Auto CAT Mgr',
       'Other', 'Auto Heavy Equipment Appraiser', 'FNOL'], dtype=object)

In [25]:
ds_adjuster_main["WFM Resource Type Desc"].unique()

array(['FRT (Property)', 'ERT (Field)', 'CAT', 'ERT (Non Field)'],
      dtype=object)

In [79]:
ds_claim_main["Weather"].unique()

NameError: name 'ds_claim_main' is not defined

In [34]:
ds_adjuster_main[["Tour Start Date", "Tour End Date"]]

,Tour Start Date,Tour End Date
0,NaN,NaN
1,NaN,NaN
2,NaN,NaN
3,NaN,NaN
4,NaN,NaN
...,...,...
769,2017-08-31 00:00:00,2017-09-15 00:00:00
770,2012-04-01 00:00:00,2012-04-01 00:00:00
771,2012-04-01 00:00:00,2012-04-02 00:00:00
772,2012-04-01 00:00:00,2012-04-02 00:00:00


In [54]:
ds_claims_main["Claim Number"].count(

np.int64(1065)

In [40]:
ds_adjuster_main["Current Status End"].sort_values(ascending=False).unique()

<DatetimeArray>
['2099-01-01 00:00:00', '2050-03-03 00:00:00', '2028-12-31 00:00:00',
 '2025-12-31 00:00:00', '2025-06-16 00:00:00', '2025-02-28 00:00:00',
 '2025-01-31 00:00:00', '2025-01-20 00:00:00', '2025-01-16 00:00:00',
 '2024-12-31 00:00:00',
 ...
 '2022-08-14 00:00:00', '2022-08-13 00:00:00', '2022-08-12 00:00:00',
 '2022-08-11 00:00:00', '2022-08-10 00:00:00', '2022-08-09 00:00:00',
 '2022-08-08 00:00:00', '2022-08-07 00:00:00', '2022-08-06 00:00:00',
 '2022-08-05 00:00:00']
Length: 193, dtype: datetime64[ns]

In [21]:
ds_claims_main["Peril Description"].unique()

array(['Wind', 'Hail', 'Water Damage - Weather', 'Lightning',
       'Water Damage - Sewer or Sump Backup', 'Flood', 'Windstorm'],
      dtype=object)

In [73]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)


table = pd.crosstab(
    ds_adjuster_main["HR Job Title"],
    ds_adjuster_main["CL Skill Level"]
)

table

CL Skill Level,0,1,2,3,4,5
HR Job Title,,,,,,
"AVP, Claim Management",1,0,0,0,0,0
"AVP, Complex Claim Liability",0,0,0,1,0,0
"AVP, Complex Claim Liability Specialist",0,0,1,0,0,0
"Account Underwriter, BSI Private Non-Profit",0,1,0,0,0,0
"Acct Exec, BC",1,0,0,0,0,0
"Assoc Acct Exec, BSI Financial Institutions",0,1,0,0,0,0
"Assoc Acct Exec, BSI Private Non-Profit",1,0,0,0,0,0
"Assoc Acct Exec, Inland",0,0,1,0,0,0
"Assoc Acct Exec, Oil & Gas",0,0,1,0,0,0


In [27]:
table = pd.crosstab(
    ds_adjuster_main["WFM Resource Type Desc"],
    ds_adjuster_main["PL Skill Level"]
)

table

PL Skill Level,0,1,2,3,4,5
WFM Resource Type Desc,,,,,,
CAT,0,0,1,7,1,1
ERT (Field),108,62,25,29,5,1
ERT (Non Field),36,7,4,21,6,4
FRT (Property),14,13,109,234,59,27


In [76]:
ds_claims_main.columns

Index(['Weather', 'Territory', 'Claim Number', 'CAT Code', 'CAT Severity Code',
       'Loss Date', 'NOL Date', 'Peril Description', 'Cause Of Injury Text',
       'Peril Group', 'Weather Indicator', 'Weather Text', 'Division',
       'Accident City', 'Accident State', 'Accident Zip', 'Claimant Number',
       'Loss Type', 'Policy Form Desc', '6_cluster_cluster_id',
       '6_cluster_distance_to_centroid_km', '7_cluster_cluster_id',
       '7_cluster_distance_to_centroid_km', '8_cluster_cluster_id',
       '8_cluster_distance_to_centroid_km', '9_cluster_cluster_id',
       '9_cluster_distance_to_centroid_km', '10_cluster_cluster_id',
       '10_cluster_distance_to_centroid_km'],
      dtype='object')

In [78]:
ds_claims_main["Weather Text"].unique()

array(['Tornado - No Flooding                                                           ',
       'Hail                                                                            ',
       'Other than Tornado, Hurricane, Tropical Storm - No Flooding                     ',
       'Flood                                                                           ',
       'Roof/Flashing Leak                                                              ',
       'Lightning (No Fire)                                                             ',
       'Other Water Damage - weather                                                    ',
       'Water Seepage in Basement not from Sewer or Sump Back-Up                        ',
       'Other than Tornado, Hurricane, Tropical Storm with Flooding                     ',
       'Hurricane or Tropical Storm - No Flooding                                       ',
       'Sump Overflow                                                                   ',